---
env:
  node: true
  es6: true

parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module

extends: eslint:recommended

rules:
  # Possible Errors
  no-console: 0

  # Best Practices
  eqeqeq: 2
  no-empty-function: 1
  no-extend-native: 2
  no-eval: 2
  no-extra-label: 2
  yoda: 1
  curly: 2

  # Stylistic Issues
  indent:
    - warn
    - 2

  quotes:
    - warn
    - single
    - allowTemplateLiterals: true

  semi:
    - warn
    - never

  eol-last:
    - warn
    - never

  func-style:
    - warn
    - declaration

  one-var:
    - warn
    - never

  operator-linebreak:
    - warn
    - after

  quote-props:
    - warn
    - consistent-as-needed

  space-before-blocks: 1
  space-in-parens: 1
  comma-style: 1
  comma-spacing: 1
  func-call-spacing: 1
  linebreak-style: 1
  no-trailing-spaces: 1
  comma-dangle: 2
  key-spacing: 1
  keyword-spacing: 1
  no-tabs: 1
  no-whitespace-before-property: 1
  object-curly-newline: 1
  object-curly-spacing: 1
  brace-style: 1

  # ECMAScript 6
  no-var: 2
  arrow-spacing: 1
  prefer-arrow-callback: 1
  prefer-const: 1
