#!/bin/sh

xConfigDir=$XDG_CONFIG_HOME/X11
userresourcesDir=$HOME/.config/Xresources
userresources=$xConfigDir/.Xresources
usermodmap=$xConfigDir/Xmodmap
xkbcomp=$xConfigDir/xkbcomp.xkb.local
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -d "$userresourcesDir" ] ; then
 for f in $userresourcesDir/* ; do
  echo $f
  xrdb -merge $f
 done
 unset f
fi
command -v xrdm > /dev/null && xrdm color nord && xrdm program rofi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#UI specific envireoment variables
export QT_STYLE_OVERRIDE=GTK+

#Load Keyboard layout (remap Caps lock to hyper key)

xkbcomp $xkbcomp $DISPLAY 

#Load Window compositor
[[ -z "$XRDP_SESSION" ]] &&
picom -b --config ~/.config/picom.conf 

#Enable the Lockscreen
xss-lock -- lock &

#Set Wallpaper
feh --bg-fill --no-fehbg "$XDG_DATA_HOME/wallpapers/cavestory.png"
#Start Apps
redshift -l 48:16 -r &
#Start Window Manager
bspwm 2> "$XDG_DATA_HOME/bspwm/bspwm.log"
