#!/bin/sh

xConfigDir=$XDG_CONFIG_HOME/X11
userresourcesDir=$HOME/.config/Xresources
userresources=$xConfigDir/.Xresources
usermodmap=$xConfigDir/Xmodmap
xkbcomp=$xConfigDir/xkbcomp.xkb
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -d "$userresourcesDir" ] ; then
 for f in $userresourcesDir/* ; do
  echo $f
  xrdb -merge $f
 done
 unset f
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Enable the Keyring
dbus-update-activation-environment --systemd DISPLAY
eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
export SSH_AUTH_SOCK

#UI specific envireoment variables
export QT_STYLE_OVERRIDE=GTK+

xkbcomp $xkbcomp $DISPLAY &
#Startup applications
picom -b --config ~/.config/picom.conf &
xss-lock -- lock &
feh --bg-fill --no-fehbg $HOME/.var/wallpapers/cavestory_1080.png
redshift -l 48:16 -r &

dwm 2> ~/.dwm.log 
