#! /bin/sh

wmname LG3D

screen -d -m -L -Logfile "$XDG_DATA_HOME/bspwm/sxhd.log" sxhkd

#Activate the Correct Keyboard Layout for the connected Keyboard

# Desktop Configuration
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a keymap-preview state=floating

