#! /bin/sh

wmname LG3D

screen -d -m sxhkd

#Activate the Correct Keyboard Layout for the connected Keyboard
doas /usr/bin/udevadm trigger --attr-match=idProduct=6060 --action=bind

# Desktop Configuration
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a keymap-preview state=floating

