"Setting Base Directories
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after


"EDITOR
set number
set nuw=4
highlight LineNr ctermfg=6
syntax on

"show netrw
:nmap <c-b> :e .<CR> 

"reload vim
:nmap <c-R> :source %<CR>

"saving
:nmap <c-s> :w<CR>
:imap <c-s> <Esc>:w<CR>a

"NETRW
let g:netrw_banner=0        " disable annoying banner
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()

set nocp
filetype plugin on

set tabstop=4
