"Setting Base Directories
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

set number
set nuw=4
highlight LineNr ctermfg=6
syntax on

:nmap <c-s> :w<CR>
:imap <c-s> <Esc>:w<CR>a

let g:netrw_banner=0

set nocp
filetype plugin on
